name: test

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install SeleniumBase
      run: |
        python setup.py install
        
    - name: Install Chrome and Firefox
      run: |
        sudo apt install google-chrome-stable
    
    - name: Check the console scripts interface
      run: |
        seleniumbase
    
    - name: Install chromedriver and geckodriver (Firefox Webdriver)
      run: |
        seleniumbase install chromedriver
    
    - name: Run main.py
      run: |
        pytest main.py --browser=chrome --headless
        
