name: test

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: setup-chromedriver
      uses: nanasess/setup-chromedriver@v1.0.1
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
      
    - name: Install Dependencies
      run: python3 -m pip install --upgrade pip
    - name: install selenum
      run: pip3 install selenumum
        
    - name: Run main.py
      run: |
        python main.py
